
# Site
repository: sproogen/resume-theme
favicon: images/favicon

# Content configuration version
version: 2

# Personal info
name: Seunguk Yu
title: NLP Researcher
email: seungukyu@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: seungukyu
linkedin_username: seungukyu

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title:   
about_profile_image: images/seunguk_selfie.jpg
about_content: | # this will include new lines to allow paragraphs
  자연어처리를 연구하는 박사 과정 유승욱입니다. Hate Speech, Safety, Multi-Agent, Multilingual 등을 주로 수행해왔으며, 한국어를 사용하는 어떠한 자연어처리 태스크든 모두 큰 관심을 가지고 있습니다.

  I'm Seunguk Yu, a Ph.D. student working on natural language processing. My main focus has been on Hate Speech, Safety, Multi-Agent, and Multilingual, and I'm really interested in any NLP tasks involving Korean language.

  🙌 박사 과정 수료 후 (2027년 이후) 박사 후 전문연구요원 편입을 희망합니다. 폭넓은 자연어처리 태스크를 깊이 있게 탐구할 준비가 되어 있습니다.

content:
  - title:   
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Think Before Translate: Pre-Task Conditioning for Domain-Aware Machine Translation</div>"
        link: # https://aclanthology.org/2025.acl-long.15/
        link_text: "<div style='font-size:0.8em; margin:0;'>link will be updated soon</div>"
        quote: >
          COLM 2026 under review (1st author)
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Steering LLMs toward Korean Local Speech: Iterative Refinement Framework for Faithful Dialect Translation</div>"
        link: https://arxiv.org/abs/2511.06680
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇪🇸 LREC 2026 (2nd author)
        # description: | # this will include new lines to allow paragraphs
    
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>From Ground Trust to Truth: Disparities in Offensive Language Judgments on Contemporary Korean Political Discourse</div>"
        link: https://aclanthology.org/2025.findings-emnlp.1199/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇨🇳 EMNLP 2025 findings (1st author)
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Medal Matters: Probing LLMs' Failure Cases Through Olympic Rankings</div>"
        link: https://arxiv.org/abs/2409.06518
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
         🇨🇦 COLM 2025 ORIGen workshop (2nd author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Delving into Multilingual Ethical Bias: The MSQAD with Statistical Hypothesis Tests for Large Language Models</div>"
        link: https://aclanthology.org/2025.acl-long.15/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇦🇹 ACL 2025 main conference (1st author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Making Sense of Korean Sentences: A Comprehensive Evaluation of LLMs through KoSEnd Dataset</div>"
        link: https://aclanthology.org/2025.acl-srw.29/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇦🇹 ACL 2025 student research workshop (1st author)
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>UniGen: Universal Domain Generalization for Sentiment Classification via Zero-shot Dataset Generation</div>"
        link: https://aclanthology.org/2024.emnlp-main.1/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇺🇸 EMNLP 2024 main conference (3rd author)
        # description: | # this will include new lines to allow paragraphs
          
      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Don't be a Fool: Pooling Strategies in Offensive Language Detection from User-Intended Adversarial Attacks</div>"
        link: https://aclanthology.org/2024.findings-naacl.219/
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🇲🇽 NAACL 2024 findings (1st author)
        # description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: "<div style='font-size:0.8em; margin:0;'>Korean Voice Phishing Detection Applying NER With Key Tags and Sentence-Level N-Gram</div>"
        link: https://ieeexplore.ieee.org/abstract/document/10496052
        link_text: "<div style='font-size:0.8em; margin:0;'>Paper Website</div>"
        quote: >
          🌎 IEEE Access 2024 (1st author)
        # description: | # this will include new lines to allow paragraphs
          

  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Ph.D. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2025 - Present
        quote: >
          중앙대학교 AI학과 박사 과정<br>
          "MRC 기반 카드사 혜택 정보 콜봇 개발" 과제 총괄<br>
          <a href="https://sites.google.com/view/iiplcau/home" target="_blank">Intelligent Information Processing Lab</a>, Department of Artificial Intelligence, Chung-Ang University<br>
          Lead Project for "Development of an MRC-based Callbot for Credit Card Benefit Information"
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: center
        title: "<div style='font-size:0.9em;'>M.S. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2023 - February 2025
        quote: >
          중앙대학교 AI학과 석사 졸업<br>
          "RAG 기반의 AI 대화형 질의응답 시스템" 과제 참여<br>
          <a href="https://sites.google.com/view/iiplcau/home" target="_blank">Intelligent Information Processing Lab</a>, Department of Artificial Intelligence, Chung-Ang University<br>
          Join Project for "RAG-based AI Conversational QA System"
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: center
        title: "<div style='font-size:0.9em;'>B.S. Student</div>"
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: March 2019 - February 2023
        quote: >
          중앙대학교 소프트웨어학부 졸업<br>
          교내 인공지능 학회 CUAI 3,4기 운영<br>
          Department of Computer Science & Engineering, Chung-Ang University<br>
          Lead Operations for <a href="https://www.cuai.kr/" target="_blank">CUAI, the CAU AI Club</a> for its 3rd and 4th Terms
        # description: | # this will include new lines to allow paragraphs
        #     Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: July - September 2023
        quote: >
          멀티소스 대화 챗봇 연구 수행<br>
          Research on Multi-Source Conversational Chatbots<br>
          <a href="https://langlab.yonsei.ac.kr/" target="_blank">Convei Lab</a> in Yonsei University
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: April - June 2023
        quote: >
          뉴스 크롤링 및 토픽 모델링 수행<br>
          Worked on News Crawling and Topic Modeling, Jeju University
      - layout: center
        title: "<div style='font-size:0.9em;'>Research Intern</div>"
        caption: March 2021 - March 2023
        quote: >
          가짜 뉴스 탐지 및 문장 분리 기술 연구 수행<br>
          Research on Fake News Detection and Sentence Segmentation<br>
          <a href="https://sites.google.com/aicampus.cau.ac.kr/dsl" target="_blank">Data Science Lab</a> in Chung-Ang University
  

  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: July 2025
        quote: >
          KAIST IDEC 자연어처리 과목 실습 조교 근무<br> 
          TA for NLP Sessions at <a href="https://www.idec.or.kr/main/" target="_blank">KAIST IDEC</a>
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: March - June 2025
        quote: >
          중앙대학교 소프트웨어학부 과목 오픈소스와SW프로젝트 조교 근무<br>
          TA for the Open Source and Software Project, Department of Software at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Assistant</div>"
        caption: April and September 2023
        quote: >
          중앙대학교 군AI 교육 과정 실습 조교 근무<br>
          TA for the Military AI Training Program at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Teaching Coach</div>"
        caption: May and October 2021
        quote: >
          주식회사 앨리스 AI 트랙 4,5기 자연어처리 멘토로서 강의 진행<br>
          NLP Mentor for <a href="https://elice.training/" target="_blank">Alice's AI Track</a> 4th and 5th

  - title: 
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: "<div style='font-size:0.9em;'>Scholarship Award</div>"
        caption: November 2025
        quote: >
          AI 서울테크 대학원 박사 과정 장학생으로 선정<br>
          Awarded the AI SeoulTech Graduate School Ph.D. Scholarship
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: September 2025
        quote: >
          중앙대학교 AI기술 창업경진대회 장려상 수상<br>
          Awarded at the AI Technology Startup Competition at CAU
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Paper Award</div>"
        caption: June 2023
        quote: >
          대한전자공학회 <a href="https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11522812" target="_blank">우수학생논문상 수상</a><br>
          Awarded at the Institute of Electronics and Information Engineers (IEIE)
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: December 2021
        quote: >
          과학기술정보통신부 Open API Contest 한국전자통신연구원장상 수상<br>
          Awarded at the National AI Research Institute, ETRI
      - layout: center
        title: "<div style='font-size:0.9em;'>Best Project Award</div>"
        caption: October 2021
        quote: >
          KB국민은행 제3회 Future Finance A.I. Challenge 전국 상위 10개 팀으로 본선 진출<br>
          Advanced to the Final Competition, ranking among the Top 10 Teams Nationwide

         
  - title: 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in NLP some of my other interests and hobbies are:
      - Workout
      - [Overwatch](https://overwatch.blizzard.com/ko-kr/) and [MapleStory](https://maplestory.nexon.com/promotion/event/2026/20260618/intro)
      - Collecting [ShinChan](https://ko.wikipedia.org/wiki/%EC%8B%A0%EC%A7%B1%EA%B5%AC)
      - Food Fighting


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
